const HideData=[
    {
        id :0,
        Title : "WordPress Themes",
        Details : 'Thousands of WordPress themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://media1.thehungryjpeg.com/thumbs2/800_3455619_cc0a1e00b6d466d6e36addfd8bf184cc08633e45_red-professional-company-brochure-template-bundle.jpg",
    },

    {
        id :1,
        Title : "eCommerce Template",
        Details : 'Beautifull Website Template',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "http://prineta.com/wp-content/uploads/2013/06/accept-international-local-payments-online-shopping-cart.gif",
    },

    {
        id :2,
        Title : "Site Templates",
        Details : 'Html and Website Tamplates',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://file.mockplus.com/image/2018/10/07d054b9-e2ea-405f-b270-23e2972b0cd7.png",
    },
    {
        id :3,
        Title : "Marketing Tamplates",
        Details : 'Email, newsletter and landing page templates',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://www.lbcngawi.com/wp-content/uploads/2020/10/DIGITAL-MARKETING.jpg",
    },
    {
        id :4,
        Title : "CMS Tamplates",
        Details : 'Over 1,700 CMS website templates',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://mockuptree.com/wp-content/uploads/2020/07/folded-business-card-mockup-4.jpg",
    },
    {
        id :5,
        Title : "Blogging",
        Details : 'Blogger templates and themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "http://thewritelife.com/wp-content/uploads/2015/04/bloggingjobs-1.png",
    },
    {
        id :6,
        Title : "Plugins",
        Details : 'Blogger templates and themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://0.s3.envato.com/files/206328777/image_core_banner-01.jpg",
    },
    {
        id :7,
        Title : "HTML",
        Details : 'Blogger templates and themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://cdn.futura-sciences.com/buildsv6/images/wide1920/8/8/1/881415294f_50170557_code-html-sashkin-adobe-stock.jpg",
    },
    {
        id :8,
        Title : "Hostion",
        Details : 'Blogger templates and themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://res.cloudinary.com/thewebmaster/image/upload/ar_2:1,c_fit,w_1200,f_auto,q_auto,r_0/image/hosting-guides-and-tutorials.png",
    },
    {
        id :9,
        Title : "Marketing",
        Details : 'Blogger templates and themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://www.kellenkautzman.com/wp-content/uploads/2017/01/shutterstock_173563757.jpg",
    },
    {
        id :10,
        Title : "UI",
        Details : 'Blogger templates and themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://i0.wp.com/www.titanui.com/wp-content/uploads/2017/09/11/HotelShopSport-Web-UI-Kits-PSD.jpg",
    },
    {
        id :11,
        Title : "HTML",
        Details : 'Blogger templates and themes',
        a1 :"Newest",
        a2 : "BestSeller",
        img : "https://cdn.futura-sciences.com/buildsv6/images/wide1920/8/8/1/881415294f_50170557_code-html-sashkin-adobe-stock.jpg",
    },
]

export default HideData;